"""Shared data contracts for I3-IoT-Edge-Cloud-Orchestrator.

This module defines the data structures that are exchanged between all
project modules (devices, infrastructure, orchestrator, and dashboard).
All modules should import from this single source of truth to ensure
consistent data formats across the system.

Example:
    from shared.schemas import Workload, ComputeResource
"""

from dataclasses import dataclass


@dataclass
class Workload:
    """Represents a computational task generated by an IoT device.

    A workload is the unit of work that the orchestrator decides where to
    place (on a device, edge node, or cloud server).

    Fields:
        id: Unique identifier for this workload.
        source_device_id: Identifier of the IoT device that generated it.
        type: Workload category, e.g. "image_processing" or "sensor_analysis".
        cpu_required: CPU cores required to execute the workload.
        memory_required: Memory (RAM) in MB required to execute it.
        data_size: Size of input data in MB.
        latency_requirement: Maximum acceptable latency in milliseconds.
        energy_requirement: Energy budget in Joules.
        priority: Urgency level (higher value = more urgent).
        model_confidence: Confidence score of the model producing the task
            (range: 0.0 to 1.0).
    """
    id: str
    source_device_id: str
    type: str
    cpu_required: float
    memory_required: float
    data_size: float
    latency_requirement: float
    energy_requirement: float
    priority: int
    model_confidence: float


@dataclass
class ComputeResource:
    """Represents a computational resource where workloads can execute.

    A single class models all three resource tiers in the system:
        - IoT device (battery-powered, limited capacity)
        - Edge node (moderate capacity, low latency)
        - Cloud server (high capacity, higher latency)

    Fields:
        id: Unique identifier for this resource.
        type: Resource tier, e.g. "device", "edge", or "cloud".
        cpu_capacity: Total CPU cores available on the resource.
        available_cpu: CPU cores currently free for new workloads.
        memory_capacity: Total memory in MB available on the resource.
        available_memory: Memory currently free in MB.
        latency: Network latency to this resource in milliseconds.
        bandwidth: Data transfer rate in MB/s.
        energy_level: Remaining battery/energy level in percent (0-100).
    """
    id: str
    type: str
    cpu_capacity: float
    available_cpu: float = None
    memory_capacity: float
    available_memory: float = None
    latency: float
    bandwidth: float
    energy_level: float = 100.0

    def __post_init__(self) -> None:
        """Apply sensible defaults for derived availability fields."""
        if self.available_cpu is None:
            self.available_cpu = self.cpu_capacity
        if self.available_memory is None:
            self.available_memory = self.memory_capacity


@dataclass
class OrchestrationDecision:
    """Represents the orchestrator's placement decision for a workload.

    Fields:
        workload_id: ID of the workload being placed.
        destination: ID of the ComputeResource selected for execution.
        score: Overall score of this placement (higher is better).
        reason: Human-readable explanation of why this destination was chosen.
    """
    workload_id: str
    destination: str
    score: float
    reason: str


@dataclass
class ExecutionFeedback:
    """Represents the measured result of executing a workload.

    This feedback is fed back to the orchestrator to improve future
    placement decisions based on real execution outcomes.

    Fields:
        workload_id: ID of the workload that was executed.
        resource_id: ID of the ComputeResource it ran on.
        success: Whether the workload completed successfully.
        execution_time: Actual time taken to execute in milliseconds.
        latency: End-to-end latency observed in milliseconds.
        cpu_used: CPU cores consumed during execution.
        memory_used: Memory consumed in MB.
        energy_used: Energy consumed in Joules.
        data_transferred: Amount of data transferred in MB.
        model_confidence: Confidence score observed after execution.
    """
    workload_id: str
    resource_id: str
    success: bool
    execution_time: float
    latency: float
    cpu_used: float
    memory_used: float
    energy_used: float
    data_transferred: float
    model_confidence: float
